# config/meta.yml
meta_product_name: "CozyMate"
meta_title: "CozyMate - Organize, Share, Win - Turn Daily Life into a Game !"
meta_description: "CozyMate, the best app to organize daily life with mates."
meta_image: "logo_cozy_mate(1).png"
